//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectX_Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectX_Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alphabet {
            get {
                object obj = ResourceManager.GetObject("Alphabet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShaderCode {
            get {
                object obj = ResourceManager.GetObject("ShaderCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sprites {
            get {
                object obj = ResourceManager.GetObject("Sprites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Alph	0	9	0
        ///!Alph	807	5	0
        ///&quot;Alph	1141	7	0
        ///#Alph	834	11	0
        ///$Alph	847	10	0
        ///%Alph	860	14	0
        ///&amp;Alph	889	11	0
        ///&apos;Alph	1124	5	0
        ///(Alph	913	7	0
        ///)Alph	922	7	0
        ///*Alph	903	7	0
        ///+Alph	996	11	0
        ///,Alph	1071	4	0
        ///-Alph	2600	16	0
        ///.Alph	3015	11	0
        ////Alph	1113	6	0
        ///0Alph	2220	23	0
        ///1Alph	1913	18	0
        ///2Alph	1945	25	0
        ///3Alph	1980	24	0
        ///4Alph	2013	26	0
        ///5Alph	2049	24	0
        ///6Alph	2083	24	0
        ///7Alph	2117	24	0
        ///8Alph	2151	24	0
        ///9Alph	2184	25	0
        ///:Alph	1063	4	0
        ///;Alph	1054	5	0
        ///&lt;Alph	1087	10	0
        ///=Alph	953	11	0
        ///&gt;Alph	1100	10	0
        ///?Alph	112 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextureIndeces {
            get {
                return ResourceManager.GetString("TextureIndeces", resourceCulture);
            }
        }
    }
}
